name: "`Type: Epic` Setup Request"
description: "Configure an automation to shadow your epics in Jira"
title: "`Type: Epic` automation setup request"
body:
  - type: input
    id: from
    attributes:
      label: "From"
      description: "A `Team: *` label in `sentry` or a repo slug"
      placeholder: "e.g. Team: Open Source -or- team-ospo"
    validations:
      required: true
  - type: input
    id: to 
    attributes:
      label: "To"
      description: "Jira project name"
      placeholder: "e.g. Open Source"
    validations:
      required: true
